name: Request Unity license

on: workflow_dispatch

jobs:
  requestLicense:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create license request
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2021.3.16f1
