name: Request Unity license

on: workflow_dispatch

jobs:
  requestLicense:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Request manual activation file (alf)
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.18f1
          activationMode: manual
          email: ${{ secrets.UNITY_EMAIL }}
